In [2]:
import numpy as np
import pandas as pd

df =pd.read_csv("cardio_preprocessed.csv")
print(df)

       gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  alco  \
0           2     168    62.0    110     80            1     1      0     0   
1           1     156    85.0    140     90            3     1      0     0   
2           1     165    64.0    130     70            3     1      0     0   
3           2     169    82.0    150    100            1     1      0     0   
4           1     156    56.0    100     60            1     1      0     0   
...       ...     ...     ...    ...    ...          ...   ...    ...   ...   
69995       2     168    76.0    120     80            1     1      1     0   
69996       1     158   126.0    140     90            2     2      0     0   
69997       2     183   105.0    180     90            3     1      0     1   
69998       1     163    72.0    135     80            1     2      0     0   
69999       1     170    72.0    120     80            2     1      0     0   

       active  cardio  
0           1       0  
1  

In [3]:
df

gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  alco  \
0           2     168    62.0    110     80            1     1      0     0   
1           1     156    85.0    140     90            3     1      0     0   
2           1     165    64.0    130     70            3     1      0     0   
3           2     169    82.0    150    100            1     1      0     0   
4           1     156    56.0    100     60            1     1      0     0   
...       ...     ...     ...    ...    ...          ...   ...    ...   ...   
69995       2     168    76.0    120     80            1     1      1     0   
69996       1     158   126.0    140     90            2     2      0     0   
69997       2     183   105.0    180     90            3     1      0     1   
69998       1     163    72.0    135     80            1     2      0     0   
69999       1     170    72.0    120     80            2     1      0     0   

       active  cardio  
0           1       0  
1           1       1  
2           0       1  
3           1       1  
4           0       0  
...       ...     ...  
69995       1       0  
69996       1       1  
69997       0       1  
69998       0       1  
69999       1       0  

[70000 rows x 11 columns]

In [4]:
df.head()


gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  alco  \
0       2     168    62.0    110     80            1     1      0     0   
1       1     156    85.0    140     90            3     1      0     0   
2       1     165    64.0    130     70            3     1      0     0   
3       2     169    82.0    150    100            1     1      0     0   
4       1     156    56.0    100     60            1     1      0     0   

   active  cardio  
0       1       0  
1       1       1  
2       0       1  
3       1       1  
4       0       0

In [5]:
df.tail()

gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  alco  \
69995       2     168    76.0    120     80            1     1      1     0   
69996       1     158   126.0    140     90            2     2      0     0   
69997       2     183   105.0    180     90            3     1      0     1   
69998       1     163    72.0    135     80            1     2      0     0   
69999       1     170    72.0    120     80            2     1      0     0   

       active  cardio  
69995       1       0  
69996       1       1  
69997       0       1  
69998       0       1  
69999       1       0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   gender       70000 non-null  int64  
 1   height       70000 non-null  int64  
 2   weight       70000 non-null  float64
 3   ap_hi        70000 non-null  int64  
 4   ap_lo        70000 non-null  int64  
 5   cholesterol  70000 non-null  int64  
 6   gluc         70000 non-null  int64  
 7   smoke        70000 non-null  int64  
 8   alco         70000 non-null  int64  
 9   active       70000 non-null  int64  
 10  cardio       70000 non-null  int64  
dtypes: float64(1), int64(10)
memory usage: 5.9 MB


In [ ]:
#Split the dataset x values

In [7]:
X = df[['gender', 'height', 'weight', 'ap_hi', 'ap_lo', 'cholesterol', 'gluc', 'smoke', 'alco', 'active' ]][:].values.reshape(70000, 10)
print(X)

[[  2. 168.  62. ...   0.   0.   1.]
 [  1. 156.  85. ...   0.   0.   1.]
 [  1. 165.  64. ...   0.   0.   0.]
 ...
 [  2. 183. 105. ...   0.   1.   0.]
 [  1. 163.  72. ...   0.   0.   0.]
 [  1. 170.  72. ...   0.   0.   1.]]


In [ ]:
#Split the dataset x values

In [8]:
y = df[['cardio']][:].values.reshape(70000, 1)
print(y)

[[0]
 [1]
 [1]
 ...
 [1]
 [1]
 [0]]


In [ ]:
#Implementing Random Forest Algorithm

In [9]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=10, criterion='gini')
model.fit(X,y)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
#Predict New data

In [10]:
new_data = [3,434,62,110,80,1,1,0,0,1]
print(model.predict([new_data]))

[1]


In [ ]:
#Simplified Code

In [10]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv("cardio_preprocessed.csv")
X = df[['gender', 'height', 'weight', 'ap_hi', 'ap_lo', 'cholesterol', 'gluc', 'smoke', 'alco', 'active' ]][:].values.reshape(70000, 10)
y = df[['cardio']][:].values.reshape(70000, 1)
model = RandomForestClassifier(n_estimators=10, criterion='gini')
model.fit(X,y)
new_data = [3,345,62,110,80,1,1,0,0,1]
print(model.predict([new_data]))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


[0]


In [ ]:
#Now its time to split train and test data

In [11]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

df = pd.read_csv("cardio_preprocessed.csv")
X_train = df[['gender', 'height', 'weight', 'ap_hi', 'ap_lo', 'cholesterol', 'gluc', 'smoke', 'alco', 'active' ]][:56000].values.reshape(56000, 10)
y_train = df[['cardio']][:56000].values.reshape(56000, 1)
X_test = df[['gender', 'height', 'weight', 'ap_hi', 'ap_lo', 'cholesterol', 'gluc', 'smoke', 'alco', 'active' ]][56000:].values.reshape(14000, 10)
y_test = df[['cardio']][56000:].values.reshape(14000, 1)

model = RandomForestClassifier(n_estimators=10, criterion='gini')
model.fit(X_train,y_train)

y_pred = model.predict(X_test)
print(classification_report(y_test,y_pred))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  if sys.path[0] == '':


              precision    recall  f1-score   support

           0       0.66      0.72      0.69      6992
           1       0.69      0.63      0.66      7008

    accuracy                           0.68     14000
   macro avg       0.68      0.68      0.68     14000
weighted avg       0.68      0.68      0.68     14000

