In [1]:
import numpy as np
import pandas as pd

df=pd.read_csv("cardio_preprocessed.csv")
print(df)

       gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  alco  \
0           2     168    62.0    110     80            1     1      0     0   
1           1     156    85.0    140     90            3     1      0     0   
2           1     165    64.0    130     70            3     1      0     0   
3           2     169    82.0    150    100            1     1      0     0   
4           1     156    56.0    100     60            1     1      0     0   
...       ...     ...     ...    ...    ...          ...   ...    ...   ...   
69995       2     168    76.0    120     80            1     1      1     0   
69996       1     158   126.0    140     90            2     2      0     0   
69997       2     183   105.0    180     90            3     1      0     1   
69998       1     163    72.0    135     80            1     2      0     0   
69999       1     170    72.0    120     80            2     1      0     0   

       active  cardio  
0           1       0  
1  

In [2]:
df

gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  alco  \
0           2     168    62.0    110     80            1     1      0     0   
1           1     156    85.0    140     90            3     1      0     0   
2           1     165    64.0    130     70            3     1      0     0   
3           2     169    82.0    150    100            1     1      0     0   
4           1     156    56.0    100     60            1     1      0     0   
...       ...     ...     ...    ...    ...          ...   ...    ...   ...   
69995       2     168    76.0    120     80            1     1      1     0   
69996       1     158   126.0    140     90            2     2      0     0   
69997       2     183   105.0    180     90            3     1      0     1   
69998       1     163    72.0    135     80            1     2      0     0   
69999       1     170    72.0    120     80            2     1      0     0   

       active  cardio  
0           1       0  
1           1       1  
2           0       1  
3           1       1  
4           0       0  
...       ...     ...  
69995       1       0  
69996       1       1  
69997       0       1  
69998       0       1  
69999       1       0  

[70000 rows x 11 columns]

In [3]:
df.head()

gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  alco  \
0       2     168    62.0    110     80            1     1      0     0   
1       1     156    85.0    140     90            3     1      0     0   
2       1     165    64.0    130     70            3     1      0     0   
3       2     169    82.0    150    100            1     1      0     0   
4       1     156    56.0    100     60            1     1      0     0   

   active  cardio  
0       1       0  
1       1       1  
2       0       1  
3       1       1  
4       0       0

In [4]:
df.tail()

gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  alco  \
69995       2     168    76.0    120     80            1     1      1     0   
69996       1     158   126.0    140     90            2     2      0     0   
69997       2     183   105.0    180     90            3     1      0     1   
69998       1     163    72.0    135     80            1     2      0     0   
69999       1     170    72.0    120     80            2     1      0     0   

       active  cardio  
69995       1       0  
69996       1       1  
69997       0       1  
69998       0       1  
69999       1       0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   gender       70000 non-null  int64  
 1   height       70000 non-null  int64  
 2   weight       70000 non-null  float64
 3   ap_hi        70000 non-null  int64  
 4   ap_lo        70000 non-null  int64  
 5   cholesterol  70000 non-null  int64  
 6   gluc         70000 non-null  int64  
 7   smoke        70000 non-null  int64  
 8   alco         70000 non-null  int64  
 9   active       70000 non-null  int64  
 10  cardio       70000 non-null  int64  
dtypes: float64(1), int64(10)
memory usage: 5.9 MB


In [ ]:
Split the dataset x values

In [6]:
X = df[['gender', 'height', 'weight', 'ap_hi', 'ap_lo', 'cholesterol', 'gluc', 'smoke', 'alco', 'active' ]][:].values.reshape(70000, 10)
print(X)

[[  2. 168.  62. ...   0.   0.   1.]
 [  1. 156.  85. ...   0.   0.   1.]
 [  1. 165.  64. ...   0.   0.   0.]
 ...
 [  2. 183. 105. ...   0.   1.   0.]
 [  1. 163.  72. ...   0.   0.   0.]
 [  1. 170.  72. ...   0.   0.   1.]]


In [ ]:
Split the dataset y values

In [7]:
y = df[['cardio']][:].values.reshape(70000, 1)
print(y)

[[0]
 [1]
 [1]
 ...
 [1]
 [1]
 [0]]


In [ ]:
 Implementing Voting Classifier Algorithm

In [8]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier, VotingClassifier
from xgboost import XGBClassifier

model1 = DecisionTreeClassifier(random_state=0)
model2 = BaggingClassifier(n_estimators=10)
model3 = XGBClassifier(n_estimators = 10)

model = VotingClassifier(estimators=[('lr', model1), ('rf', model2), ('gnb', model3)], voting='hard')
model.fit(X,y)

ModuleNotFoundError: No module named 'xgboost'

In [9]:
!pip install xgboost