In [1]:
import numpy as np 
import pandas as pd

df =pd.read_csv("cardio_preprocessed.csv")
print(df)

       gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  alco  \
0           2     168    62.0    110     80            1     1      0     0   
1           1     156    85.0    140     90            3     1      0     0   
2           1     165    64.0    130     70            3     1      0     0   
3           2     169    82.0    150    100            1     1      0     0   
4           1     156    56.0    100     60            1     1      0     0   
...       ...     ...     ...    ...    ...          ...   ...    ...   ...   
69995       2     168    76.0    120     80            1     1      1     0   
69996       1     158   126.0    140     90            2     2      0     0   
69997       2     183   105.0    180     90            3     1      0     1   
69998       1     163    72.0    135     80            1     2      0     0   
69999       1     170    72.0    120     80            2     1      0     0   

       active  cardio  
0           1       0  
1  

In [2]:
df

gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  alco  \
0           2     168    62.0    110     80            1     1      0     0   
1           1     156    85.0    140     90            3     1      0     0   
2           1     165    64.0    130     70            3     1      0     0   
3           2     169    82.0    150    100            1     1      0     0   
4           1     156    56.0    100     60            1     1      0     0   
...       ...     ...     ...    ...    ...          ...   ...    ...   ...   
69995       2     168    76.0    120     80            1     1      1     0   
69996       1     158   126.0    140     90            2     2      0     0   
69997       2     183   105.0    180     90            3     1      0     1   
69998       1     163    72.0    135     80            1     2      0     0   
69999       1     170    72.0    120     80            2     1      0     0   

       active  cardio  
0           1       0  
1           1       1  
2           0       1  
3           1       1  
4           0       0  
...       ...     ...  
69995       1       0  
69996       1       1  
69997       0       1  
69998       0       1  
69999       1       0  

[70000 rows x 11 columns]

In [3]:
df.head()

gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  alco  \
0       2     168    62.0    110     80            1     1      0     0   
1       1     156    85.0    140     90            3     1      0     0   
2       1     165    64.0    130     70            3     1      0     0   
3       2     169    82.0    150    100            1     1      0     0   
4       1     156    56.0    100     60            1     1      0     0   

   active  cardio  
0       1       0  
1       1       1  
2       0       1  
3       1       1  
4       0       0

In [4]:
df.tail()

gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  alco  \
69995       2     168    76.0    120     80            1     1      1     0   
69996       1     158   126.0    140     90            2     2      0     0   
69997       2     183   105.0    180     90            3     1      0     1   
69998       1     163    72.0    135     80            1     2      0     0   
69999       1     170    72.0    120     80            2     1      0     0   

       active  cardio  
69995       1       0  
69996       1       1  
69997       0       1  
69998       0       1  
69999       1       0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   gender       70000 non-null  int64  
 1   height       70000 non-null  int64  
 2   weight       70000 non-null  float64
 3   ap_hi        70000 non-null  int64  
 4   ap_lo        70000 non-null  int64  
 5   cholesterol  70000 non-null  int64  
 6   gluc         70000 non-null  int64  
 7   smoke        70000 non-null  int64  
 8   alco         70000 non-null  int64  
 9   active       70000 non-null  int64  
 10  cardio       70000 non-null  int64  
dtypes: float64(1), int64(10)
memory usage: 5.9 MB


In [5]:
df.describe()

gender        height        weight         ap_hi         ap_lo  \
count  70000.000000  70000.000000  70000.000000  70000.000000  70000.000000   
mean       1.349571    164.359229     74.205690    128.817286     96.630414   
std        0.476838      8.210126     14.395757    154.011419    188.472530   
min        1.000000     55.000000     10.000000   -150.000000    -70.000000   
25%        1.000000    159.000000     65.000000    120.000000     80.000000   
50%        1.000000    165.000000     72.000000    120.000000     80.000000   
75%        2.000000    170.000000     82.000000    140.000000     90.000000   
max        2.000000    250.000000    200.000000  16020.000000  11000.000000   

        cholesterol          gluc         smoke          alco        active  \
count  70000.000000  70000.000000  70000.000000  70000.000000  70000.000000   
mean       1.366871      1.226457      0.088129      0.053771      0.803729   
std        0.680250      0.572270      0.283484      0.225568      0.397179   
min        1.000000      1.000000      0.000000      0.000000      0.000000   
25%        1.000000      1.000000      0.000000      0.000000      1.000000   
50%        1.000000      1.000000      0.000000      0.000000      1.000000   
75%        2.000000      1.000000      0.000000      0.000000      1.000000   
max        3.000000      3.000000      1.000000      1.000000      1.000000   

             cardio  
count  70000.000000  
mean       0.499700  
std        0.500003  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        1.000000  
max        1.000000

In [ ]:
Split the dataset x values

In [6]:
X = df[['gender', 'height', 'weight', 'ap_hi', 'ap_lo', 'cholesterol', 'gluc', 'smoke', 'alco', 'active' ]][:].values.reshape(70000, 10)
print(X)

[[  2. 168.  62. ...   0.   0.   1.]
 [  1. 156.  85. ...   0.   0.   1.]
 [  1. 165.  64. ...   0.   0.   0.]
 ...
 [  2. 183. 105. ...   0.   1.   0.]
 [  1. 163.  72. ...   0.   0.   0.]
 [  1. 170.  72. ...   0.   0.   1.]]


In [ ]:
Split the dataset x values

In [7]:
y = df[['cardio']][:].values.reshape(70000, 1)
print(y)

[[0]
 [1]
 [1]
 ...
 [1]
 [1]
 [0]]


In [ ]:
Implementing XGBClassifier Algorithm

In [8]:
from sklearn.ensemble import BaggingClassifier

model = BaggingClassifier(n_estimators=10, random_state=0)
model.fit(X,y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\_bagging.py:645: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BaggingClassifier(base_estimator=None, bootstrap=True, bootstrap_features=False,
                  max_features=1.0, max_samples=1.0, n_estimators=10,
                  n_jobs=None, oob_score=False, random_state=0, verbose=0,
                  warm_start=False)

In [ ]:
Predict New data

In [10]:
new_data = [2,168,62,110,80,1,1,0,0,1]
print(model.predict([new_data]))

[0]


In [ ]:
Simplified Code

In [11]:
import pandas as pd
from sklearn.ensemble import BaggingClassifier

df = pd.read_csv("cardio_preprocessed.csv")
X = df[['gender', 'height', 'weight', 'ap_hi', 'ap_lo', 'cholesterol', 'gluc', 'smoke', 'alco', 'active' ]][:].values.reshape(70000, 10)
y = df[['cardio']][:].values.reshape(70000, 1)
model = BaggingClassifier(n_estimators=10, random_state=0)
model.fit(X,y)
new_data = [2,168,62,110,80,1,1,0,0,1]
print(model.predict([new_data]))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\_bagging.py:645: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[0]


In [ ]:
A Better Approach 

In [ ]:
Now its time to split train and test data

In [ ]:
Working with the same dataset by splitting train and test data

In [9]:
import pandas as pd
from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import classification_report

df = pd.read_csv("cardio_preprocessed.csv")
X_train = df[['gender', 'height', 'weight', 'ap_hi', 'ap_lo', 'cholesterol', 'gluc', 'smoke', 'alco', 'active' ]][:56000].values.reshape(56000, 10)
y_train = df[['cardio']][:56000].values.reshape(56000, 1)
X_test = df[['gender', 'height', 'weight', 'ap_hi', 'ap_lo', 'cholesterol', 'gluc', 'smoke', 'alco', 'active' ]][56000:].values.reshape(14000, 10)
y_test = df[['cardio']][56000:].values.reshape(14000, 1)

model = BaggingClassifier(n_estimators=10, random_state=0)
model.fit(X_train,y_train)

y_pred = model.predict(X_test)
print(classification_report(y_test,y_pred))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\_bagging.py:645: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


              precision    recall  f1-score   support

           0       0.65      0.71      0.68      6992
           1       0.68      0.62      0.65      7008

    accuracy                           0.67     14000
   macro avg       0.67      0.67      0.67     14000
weighted avg       0.67      0.67      0.67     14000

